### ISSUE TITLE
Cannot seek to end of data object replica stored on S3

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_resource_plugin_s3#2020] opened 2021-12-21 06:35 UTC
- [x] main
- [x] 4-2-stable
-----
We're using  iRODS 4.2.11 and the S3 storage plugin (4.2.11.0) as released, and using the `minio/minio` docker image to create an S3 storage resource:
```
$ docker run -d  -e MINIO_ROOT_USER=<ACCESS_ID> -e MINIO_ROOT_PASSWORD=<SECRET> -p 9000:9000   -p 9001:9001   minio/minio server /data --console-address ":9001" 
$ iadmin mkresc s3resc s3 $(hostname):/irods/ \
"S3_DEFAULT_HOSTNAME=localhost:9000;"\
"S3_AUTH_FILE=/var/lib/irods/credentials;"\
"S3_REGIONNAME=us-east-1;"\
"S3_RETRY_COUNT=1;"\
"S3_WAIT_TIME_SEC=3;"\
"S3_PROTO=HTTP;"\
"ARCHIVE_NAMING_POLICY=consistent;"\
"HOST_MODE=cacheless_attached"
```
**Background** 
For a GET operation the multi-1247 parallel transfer engine (PTE) as implemented in the Python iRODS Client (PRC) depends on a data object seek-to-end, and an immediate tell ( ) call, to determine the size of the object to be downloaded, so that it can decide between single-thread and parallel modes of transfer.  However, an end-of-object seek now throws an error from PRC when the voting for READ returns the S3 replica.

**Demo of problem** 
To distill down code from PRC get( ) to the minimum that reproduces the error, consider this PRC script (`seek.py`):
```python
#!/usr/bin/env python
from irods.test.helpers import make_session
import sys
import os
obj_path = sys.argv[1]
with make_session() as ses:
    with ses.data_objects.open(obj_path,'r') as d:
        size = d.seek(0, os.SEEK_END)
        print('size of object =', size)
```
Then let us put a large file and try to seek it from Python:
```
$ dd if=/dev/urandom  of=largeFile bs=1k count=39k
$ iput -R s3resc largeFile
$ python seek.py $(ipwd)/largeFile
```
Doing so will produce this error dump at the client end:
```
$ python seek.py $(ipwd)/largeFile
Traceback (most recent call last):
  File "seek.py", line 9, in <module>
    size = d.seek(0, os.SEEK_END)
  File "/home/daniel/python-irodsclient/irods/data_object.py", line 180, in seek
    return self.conn.seek_file(self.desc, offset, whence)
  File "/home/daniel/python-irodsclient/irods/connection.py", line 553, in seek_file
    response = self.recv()
  File "/home/daniel/python-irodsclient/irods/connection.py", line 114, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.UnknowniRODSError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "seek.py", line 10, in <module>
    print('size of object =', size)
  File "/home/daniel/python-irodsclient/irods/data_object.py", line 180, in seek
    return self.conn.seek_file(self.desc, offset, whence)
  File "/home/daniel/python-irodsclient/irods/connection.py", line 553, in seek_file
    response = self.recv()
  File "/home/daniel/python-irodsclient/irods/connection.py", line 114, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.UnknowniRODSError: None
```
... while no errors or warnings are produced in the server rodsLog.

But, if we replicate to demoResc (the default resc) and repeat the seek operation, voting favors the non-S3 replica and everything runs  without error:
```
$ irepl -R demoResc largeFile
$ python seek.py $(ipwd)/largeFile
size of object = 40894464
```

**Comment by d-w-moore** [comment] 2021-12-21 12:54
Since looking back at our [lightning talk](https://youtu.be/eNnJecHgkwM?t=413) where we demonstrated he PRC parallel PUT (in the demo we actually used iget, not PRC's ` data_object_manager.get( )`, to re-download and verify the object's integrity), I decided to track the `python3 seek.py $(ipwd)/largeFile` back through S3 plugin versions, with these results:
```
___S3 VERSION__         __OUTPUT of seek.py__
version == 4.2.8.1      size of object = 40894464
version == 4.2.9.0      size of object = 0
version == 4.2.9.1      <error dump as above>
```

**Comment by JustinKyleJames** [comment] 2022-01-04 19:06
This is caused by an unknown object size when seeking to the end.  To resolve this, I updated the code to do a HEAD to get the current object size if it is not known.

The object size being used is a setting that the transport client sets when opening an object for writing.  It is the expected file size after writing and is used to determine how the parts will be broken up by threads.  In the test case above, the object already existed so the transport client had no need to set the file size.

This differed from the unit tests where the file was written and then seek was performed in the same transport object.  I will expand the unit tests to cover the case where the file already existed before the transport object was created.

**Comment by trel** [comment] 2022-01-11 03:14
@d-w-moore please confirm - and we'll close this.

**Comment by d-w-moore** [comment] 2022-01-11 13:36
Will run test suite and then confirm ok for merge.

**Comment by d-w-moore** [comment] 2022-01-11 14:30
This is fine, tested it manually - so merge away....  
Will test the corresponding PRC changes in that test suite before merge into that release.

**Comment by trel** [comment] 2022-01-11 14:32
it's already merged - closing the issue now.

**Closed by trel** 2022-01-11 14:32 UTC
Labels: bug
